### ISSUE TITLE
Lägg till header med Universitet och Sidnummer

### ISSUE THREAD

**Issue by exoji2e** [EinPy/Competetive-Progrmming-Notebook#1]
Se exempelvis kactl: https://github.com/kth-competitive-programming/kactl/blob/main/kactl.pdf

Universitet till höger: Lund University
Pagenumber till vänster.

Kactl gör såhär:
```
\renewcommand{\headrulewidth}{0pt}
\headheight 25pt
\lhead{\@unishort}
\chead{\immediate\write18{python2 content/tex/preprocessor.py --print-header "\splitbotmarks\hdrmark|\botmarks\hdrmark" -o \@builddir/header2.tmp}\immediate\input{\@builddir/header2.tmp}}
\rhead{\thepage}
```
(skippa förslagsvis `\chead`-delen)

**Comment by EinPy** [comment]
Nice, skal fiksa det

søn. 20. nov. 2022 kl. 19:35 skrev Måns Magnusson ***@***.***

**Comment by EinPy** [comment]
Fikk legga til
```
\patchcmd{\titlepage}{empty}{fancy}{}{}
\patchcmd{\chapter}{plain}{fancy}{}{}
```
ochså men nu funkar det.
